---
# This playbook deploys the whole application stack in this site.

- name: apply common configuration to all hosts
  hosts: all
  remote_user: root
  #remote_user: adminuser
  #become: True
  #become_method: sudo

  roles:
    - common

- name: Deploy the nimiq miner
  hosts: nimiq-miner
  remote_user: root
  #remote_user: adminuser
  #become: True
  #become_method: sudo

  roles:
    - letsencrypt
    - miner
    - monitor

